version: '3'

services:
  node:
    container_name: websocket_server
    image: 'node:16-alpine'
    volumes:
      - '.:/home/app'
    ports:
      - '3000:3000'
    working_dir: /home/app
    networks:
      - app-network
    command: 'npm run serve'

networks:
  app-network:
    external:
      name: radar_network
